# Generated by Django 2.0.2 on 2019-11-19 04:04

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_photo', pyuploadcare.dj.models.ImageField(help_text='This is a photo for the about section', null=True, verbose_name='Professional Photo')),
                ('section_title', models.CharField(default='About Me', help_text='Title for the about section.', max_length=50, verbose_name='Section Title')),
                ('description', models.TextField(help_text='This is the description for the about section.', null=True)),
                ('background_image', pyuploadcare.dj.models.ImageField(help_text='This is the background image for the about section', null=True, verbose_name='Background Image')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
