"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""


import os
from pathlib import Path
from os.path import join

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
gettext = lambda s: s
PROJECT_PATH = os.path.split(os.path.abspath(os.path.dirname(__file__)))[0]

# Application definition
INSTALLED_APPS = [
    'jazzmin', # keep before django.contrib.admin

    'django.contrib.sites',

    # key django CMS modules
    'cms',
    'menus',
    'treebeard',
    'sekizai',

    # Django Filer - optional, but used in most projects
    'filer',
    'easy_thumbnails',

    # the default CKEditor - optional, but used in most projects
    'djangocms_text_ckeditor',

    # some content plugins - optional, but used in most projects
    'djangocms_file',
    'djangocms_icon',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_googlemap',
    'djangocms_video',
    'djangocms_forms',

    # optional django CMS Bootstrap 4 modules
    'djangocms_bootstrap4',
    'djangocms_bootstrap4.contrib.bootstrap4_alerts',
    'djangocms_bootstrap4.contrib.bootstrap4_badge',
    'djangocms_bootstrap4.contrib.bootstrap4_card',
    'djangocms_bootstrap4.contrib.bootstrap4_carousel',
    'djangocms_bootstrap4.contrib.bootstrap4_collapse',
    'djangocms_bootstrap4.contrib.bootstrap4_content',
    'djangocms_bootstrap4.contrib.bootstrap4_grid',
    'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
    'djangocms_bootstrap4.contrib.bootstrap4_link',
    'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
    'djangocms_bootstrap4.contrib.bootstrap4_media',
    'djangocms_bootstrap4.contrib.bootstrap4_picture',
    'djangocms_bootstrap4.contrib.bootstrap4_tabs',
    'djangocms_bootstrap4.contrib.bootstrap4_utilities',

    # Default
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party
    'ckeditor',
    'ckeditor_uploader',
    'nested_admin',
    'nested_inline',
    'clear_cache',
    'phone_field',

    # My Apps
    'user.apps.UserConfig',
    'contact.apps.ContactConfig',
    'home.apps.HomeConfig',
    'lots.apps.LotsConfig',
    'rates.apps.RatesConfig',
    'sections.apps.SectionsConfig',
    'reserve.apps.ReserveConfig',
    'blog.apps.BlogConfig',
    'events.apps.EventsConfig',
    'gallery.apps.GalleryConfig',
    'ownership.apps.OwnershipConfig',
    'specials.apps.SpecialsConfig',
    'beach_access.apps.BeachAccessConfig',
    'garv.apps.GarvConfig',

]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    ### DJANGO CMS ###
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [join(BASE_DIR, 'templates'), 'home/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                ### DJANGO CMS ###
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'django.template.context_processors.i18n',
                'cms.context_processors.cms_settings',
                'sekizai.context_processors.sekizai',
            ],
            'libraries': {
                'home_tags': 'home.templatetags.home_tags',
                'gallery_tags': 'gallery.templatetags.gallery_tags',
            },
        },
    },
]


WSGI_APPLICATION = 'main.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
]

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/


# Collect media files here
MEDIA_URL = '/media/'
MEDIA_ROOT = join(BASE_DIR, 'deployment', 'media')

# look for static assets here

STATIC_URL = '/static/'
STATIC_ROOT = join(BASE_DIR, 'deployment', 'static')

STATICFILES_DIRS = [
    join(BASE_DIR, 'static'),
    join(BASE_DIR, 'lots/static/lots'),
]
##################
# .ENV VARIABLES #
##################
from dotenv import load_dotenv
load_dotenv()

##############
# UPLOADCARE #
##############
UPLOADCARE = {
    'pub_key': os.getenv('UPLOADCARE_PUB_KEY'),
    'secret': os.getenv('UPLOADCARE_SECRET_KEY'),
}
UPLOADCARE_INPUT_ACCEPT_TYPES = '*.mp4'

UPLOADCARE_LOCALE_TRANSLATIONS = {
        'errors': {'fileType': 'This type of files is not allowed.'},
      }


##############
# CKEDITOR #
##############
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'
CKEDITOR_UPLOAD_PATH = "richtext-upload"
CKEDITOR_RESTRICT_BY_USER = False
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'skin':'moono-dark', 
        'width': '100%',
        'height': '100%',
        'fillEmptyBlocks': 'false',
        'autoParagraph': 'false',
        'removeDialogTabs': 'link:advanced',
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'clipboard', 'items': [ '-', 'Undo', 'Redo']},
            {'name': 'yourcustomtools', 'items': [
                'Preview',
                'Maximize',
            ]},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']}, 
            {'name': 'links', 'items': ['Link', 'Unlink', 'EasyImageUpload']},
            {'name': 'insert',
             'items': ['Table', 'HorizontalRule', 'Smiley']},

            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            '/',  

        ],
        'toolbar': 'YourCustomToolbarConfig',
        'cloudServices_uploadUrl': 'https://75887.cke-cs.com/easyimage/upload/',
        'cloudServices_tokenUrl': 'https://75887.cke-cs.com/token/dev/da235fb3000c6efdce9bcdbd07c7ebbefd260f9753651dc5bbd5e596e5d1',
        'easyimage_styles': {
            'gradient1': {
            'group': 'easyimage-gradients',
            'attributes': {
                'class': 'easyimage-gradient-1'
            },
            'label': 'Blue Gradient',
            'icon': 'https://ckeditor.com/docs/ckeditor4/4.15.0/examples/assets/easyimage/icons/gradient1.png',
            'iconHiDpi': 'https://ckeditor.com/docs/ckeditor4/4.15.0/examples/assets/easyimage/icons/hidpi/gradient1.png'
            },
            'gradient2': {
            'group': 'easyimage-gradients',
            'attributes': {
                'class': 'easyimage-gradient-2'
            },
            'label': 'Pink Gradient',
            'icon': 'https://ckeditor.com/docs/ckeditor4/4.15.0/examples/assets/easyimage/icons/gradient2.png',
            'iconHiDpi': 'https://ckeditor.com/docs/ckeditor4/4.15.0/examples/assets/easyimage/icons/hidpi/gradient2.png'
            },
            'noGradient': {
            'group': 'easyimage-gradients',
            'attributes': {
                'class': 'easyimage-no-gradient'
            },
            'label': 'No Gradient',
            'icon': 'https://ckeditor.com/docs/ckeditor4/4.15.0/examples/assets/easyimage/icons/nogradient.png',
            'iconHiDpi': 'https://ckeditor.com/docs/ckeditor4/4.15.0/examples/assets/easyimage/icons/hidpi/nogradient.png'
            }
      },
      'easyimage_toolbar': [
        'EasyImageFull',
        'EasyImageSide',
        'EasyImageGradient1',
        'EasyImageGradient2',
        'EasyImageNoGradient',
        'EasyImageAlt'
      ],
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',
            'easyimage',
            'imagebase',
            'cloudservices',
            'balloontoolbar',
            'balloonpanel',
            'autogrow',
            'pastefromword'
        ]),
        'removePlugins': ','.join([
            'image',
        ]),

    }
}


##############
# JAZZMIN #
##############
JAZZMIN_SETTINGS = {

    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Buena Vista",

    # Title on the brand, and login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Admin",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "images/buena-vista/logos/logo-colors.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Buena Vista Admin",

    # Copyright on the footer
    "copyright": "Ben Hutton",

    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": "auth.User",

    # Field name on user model that contains avatar image
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    # Links to put along the top menu
    "topmenu_links": [

        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        # {"app": "events"},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    #############
    # Side Menu #
    #############

    'order_with_respect_to' : ['auth', 'user', 'sections', 'lots',  'blog', 'events', 'gallery', 'ownership', 'rates', 'reserve', 'specials', 'garv', 'contact', ],


    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": False,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": ['sites', 'cms','filer', 'djangocms_forms'],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": ['cms.pagetype', 'cms.staticplaceholder'],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    # "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    # "custom_links": {
    #     "events": [{
    #         "name": "Make Messages", 
    #         "url": "make_messages", 
    #         "icon": "fas fa-comments",
    #         "permissions": ["books.view_book"]
    #     }]
    # },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": 'admin/css/custom_admin.css',
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    # Add a language dropdown into the admin
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    # "dark_mode_theme": "darkly",
}


###############
# DJANGO CMS #
###############
CMS_TEMPLATES = [
    # ('cms/base.html', 'Base'),

    # a minimal template to get started with
    ('cms/minimal.html', 'Minimal template'),

    # optional templates that extend base.html, to be used with Bootstrap 4
    ('cms/page.html', 'Page'),
    ('cms/feature.html', 'Page with Feature'),

]

EMAIL_HOST = 'smtp.gmail.com'  # since you are using a gmail account
EMAIL_PORT = 587  # Gmail SMTP port for TLS
EMAIL_USE_TLS = True    



try:
    from main.local_settings import *
except:
    pass 


