# Generated by Django 2.0.2 on 2019-07-16 23:39

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('image', pyuploadcare.dj.models.ImageField(null=True)),
                ('left_text', models.TextField(blank=True, default='', max_length=200)),
                ('on_break', models.CharField(blank=True, max_length=50, null=True)),
                ('right_title', models.CharField(blank=True, default='', max_length=50)),
                ('right_text', models.TextField(blank=True, default='', max_length=200)),
                ('number_of_progress_bars', models.IntegerField(blank=True, default=0)),
                ('progress_bar_title_1', models.CharField(blank=True, max_length=20, null=True)),
                ('progress_bar_title_2', models.CharField(blank=True, max_length=20, null=True)),
                ('progress_bar_title_3', models.CharField(blank=True, max_length=20, null=True)),
                ('progress_bar_title_4', models.CharField(blank=True, max_length=20, null=True)),
                ('name_and_signature', models.BooleanField(default=True)),
                ('signature_file', models.FileField(blank=True, default='', upload_to='signature/')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.CharField(blank=True, default='', max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', pyuploadcare.dj.models.ImageField(null=True)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('on_break', models.CharField(blank=True, default='', max_length=50)),
                ('background', pyuploadcare.dj.models.ImageField(null=True)),
                ('video_modal', models.BooleanField(default=False)),
                ('youtube_url', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Header',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(blank=True, default='', max_length=150)),
                ('instagram_link', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='TypedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', pyuploadcare.dj.models.ImageField(null=True)),
                ('static_text', models.CharField(blank=True, default='', max_length=50)),
                ('typed_text_1', models.CharField(blank=True, default='', max_length=50)),
                ('typed_text_2', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Background (Typed Text)',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_portfolio.Portfolio')),
                ('photo', pyuploadcare.dj.models.ImageField(null=True, verbose_name='image')),
                ('category', models.CharField(default='', max_length=50)),
                ('cat_link', models.CharField(default='', max_length=50)),
                ('slot_number', models.CharField(blank=True, choices=[('None', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='None', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('home_portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='SectionTitle',
            fields=[
                ('services_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_portfolio.Services')),
                ('title', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Services Main Title',
            },
            bases=('home_portfolio.services',),
        ),
        migrations.CreateModel(
            name='SectionTitleDescription',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_portfolio.Portfolio')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Title & Description',
            },
            bases=('home_portfolio.portfolio',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('services_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_portfolio.Services')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=200)),
                ('icon', models.FileField(default='None', upload_to='icons/')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('home_portfolio.services',),
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('portfolio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home_portfolio.Portfolio')),
                ('slide_photo', pyuploadcare.dj.models.ImageField(null=True, verbose_name='image')),
                ('category', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Slideshow',
            },
            bases=('home_portfolio.portfolio',),
        ),
        migrations.AddField(
            model_name='services',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_home_portfolio.services_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_home_portfolio.portfolio_set+', to='contenttypes.ContentType'),
        ),
    ]
