# Generated by Django 2.0.2 on 2019-11-19 04:04

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True, help_text='Check to display this section.', verbose_name='Display This Section')),
                ('bg', pyuploadcare.dj.models.ImageField(help_text='Background Image.', null=True, verbose_name='Background')),
                ('intro', models.CharField(help_text='A short intro.', max_length=100, null=True)),
                ('name', models.CharField(help_text='Your Name.', max_length=100, null=True)),
                ('navlogo', pyuploadcare.dj.models.ImageField(help_text='Logo that appears in the top left corner of the Navigation Bar.', null=True, verbose_name='Nav Logo')),
                ('logo', pyuploadcare.dj.models.ImageField(help_text='The logo that will be used if you use the "Logo Styled Header Option".', null=True, verbose_name='logo')),
                ('style', models.CharField(choices=[('simple', 'simple'), ('textbox', 'textbox'), ('animated', 'animated'), ('logo', 'logo')], default='animated', help_text='The style header you want to use.', max_length=50, verbose_name='Style')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
    ]
