# Generated by Django 2.0.2 on 2019-11-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True, help_text='Check to display this section.', verbose_name='Display This Section')),
                ('section_title', models.CharField(default='Get in touch', help_text='Title for this section.', max_length=50)),
                ('address', models.CharField(help_text='Your address.', max_length=50, null=True)),
                ('phone', models.CharField(help_text='Your phone number', max_length=50, null=True)),
                ('email', models.CharField(help_text='Your email.', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
