# Generated by Django 2.0.2 on 2019-11-19 04:04

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', pyuploadcare.dj.models.ImageField(help_text='Background image for the events header.', null=True)),
                ('header_title', models.CharField(default='Events', help_text='Title for the events header.', max_length=50)),
                ('title', models.CharField(help_text='Title for the event.', max_length=50, null=True)),
                ('description', models.TextField(help_text='Description for the event.', max_length=650, null=True)),
                ('image', pyuploadcare.dj.models.ImageField(help_text='Main image for the event post.', null=True)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', pyuploadcare.dj.models.ImageField(verbose_name='Image')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
