# Generated by Django 2.0.2 on 2019-11-19 04:04

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True, help_text='Check to show this section on the home page', verbose_name='Display This Section')),
                ('title', models.CharField(help_text='Title for this post', max_length=100, null=True)),
                ('description', models.CharField(help_text='Description of this shopping category', max_length=100, null=True)),
                ('thumbnail', pyuploadcare.dj.models.ImageField(help_text='Image to display', null=True, verbose_name='thumbnail')),
                ('category', models.CharField(choices=[('all artwork', 'all artwork'), ('originals', 'originals'), ('prints', 'prints')], help_text='Category of Art', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shop',
            },
        ),
    ]
