# Generated by Django 2.0.2 on 2019-11-19 04:04

from django.db import migrations, models
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True, help_text='Check to display this section.', verbose_name='Display This Section')),
                ('section_title', models.CharField(default='Gallery', help_text='Title for this section.', max_length=50)),
                ('title', models.CharField(help_text='Image Title.', max_length=100, null=True)),
                ('image', pyuploadcare.dj.models.ImageField(help_text='Image to display for gallery', null=True)),
                ('category', models.CharField(help_text='Image Category', max_length=100, null=True)),
                ('style', models.CharField(choices=[('staggered', 'staggered'), ('even', 'even')], default='staggred', help_text='Gallery style.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
