# Generated by Django 2.0.2 on 2019-11-19 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=300, null=True)),
                ('image_title', models.CharField(max_length=100, null=True)),
                ('image_category', models.CharField(max_length=100, null=True)),
                ('image_sub_category', models.CharField(max_length=100, null=True)),
                ('image_price', models.CharField(max_length=20, null=True)),
                ('image_description', models.TextField(null=True)),
                ('usr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CartBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', pyuploadcare.dj.models.ImageField(help_text='Background image for the header of the Cart Checkout Page.', null=True)),
                ('header_title', models.CharField(default='Shopping Cart', help_text='Title that is displayed over the background image.', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
