# Generated by Django 2.0.2 on 2019-12-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
