# Generated by Django 2.0.2 on 2019-12-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=300, null=True)),
                ('bought', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sold',
        ),
    ]
