# Generated by Django 2.0.2 on 2019-12-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20191203_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sold',
        ),
    ]
